/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAreasRouteImport } from './routes/app/areas'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppDepartmentsRouteImport } from './routes/app/departments'
import { Route as AppHoursRouteImport } from './routes/app/hours'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppOverdueRouteImport } from './routes/app/overdue'
import { Route as AppRequestsRouteImport } from './routes/app/requests'
import { Route as AppRoomsRouteImport } from './routes/app/rooms'
import { Route as AppSitesRouteImport } from './routes/app/sites'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AppWorkersRouteImport } from './routes/app/workers'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AppRequestsIdRouteImport } from './routes/app/requests_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAreasRoute = AppAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppHoursRoute = AppHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOverdueRoute = AppOverdueRouteImport.update({
  id: '/overdue',
  path: '/overdue',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests_/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/worker': typeof WorkerRoute
  '/app/areas': typeof AppAreasRoute
  '/app/audit': typeof AppAuditRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/hours': typeof AppHoursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overdue': typeof AppOverdueRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/workers': typeof AppWorkersRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/worker': typeof WorkerRoute
  '/app/areas': typeof AppAreasRoute
  '/app/audit': typeof AppAuditRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/hours': typeof AppHoursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overdue': typeof AppOverdueRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/workers': typeof AppWorkersRoute
  '/r/$code': typeof RCodeRoute
  '/app': typeof AppIndexRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/worker': typeof WorkerRoute
  '/app/areas': typeof AppAreasRoute
  '/app/audit': typeof AppAuditRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/hours': typeof AppHoursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overdue': typeof AppOverdueRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/workers': typeof AppWorkersRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/requests_/$id': typeof AppRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/worker'
    | '/app/areas'
    | '/app/audit'
    | '/app/departments'
    | '/app/hours'
    | '/app/notifications'
    | '/app/overdue'
    | '/app/requests'
    | '/app/rooms'
    | '/app/sites'
    | '/app/staff'
    | '/app/workers'
    | '/r/$code'
    | '/app/'
    | '/app/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/worker'
    | '/app/areas'
    | '/app/audit'
    | '/app/departments'
    | '/app/hours'
    | '/app/notifications'
    | '/app/overdue'
    | '/app/requests'
    | '/app/rooms'
    | '/app/sites'
    | '/app/staff'
    | '/app/workers'
    | '/r/$code'
    | '/app'
    | '/app/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/worker'
    | '/app/areas'
    | '/app/audit'
    | '/app/departments'
    | '/app/hours'
    | '/app/notifications'
    | '/app/overdue'
    | '/app/requests'
    | '/app/rooms'
    | '/app/sites'
    | '/app/staff'
    | '/app/workers'
    | '/r/$code'
    | '/app/'
    | '/app/requests_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkerRoute: typeof WorkerRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/areas': {
      id: '/app/areas'
      path: '/areas'
      fullPath: '/app/areas'
      preLoaderRoute: typeof AppAreasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hours': {
      id: '/app/hours'
      path: '/hours'
      fullPath: '/app/hours'
      preLoaderRoute: typeof AppHoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overdue': {
      id: '/app/overdue'
      path: '/overdue'
      fullPath: '/app/overdue'
      preLoaderRoute: typeof AppOverdueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers': {
      id: '/app/workers'
      path: '/workers'
      fullPath: '/app/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/requests_/$id': {
      id: '/app/requests_/$id'
      path: '/requests/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAreasRoute: typeof AppAreasRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppHoursRoute: typeof AppHoursRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverdueRoute: typeof AppOverdueRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppWorkersRoute: typeof AppWorkersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAreasRoute: AppAreasRoute,
  AppAuditRoute: AppAuditRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppHoursRoute: AppHoursRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverdueRoute: AppOverdueRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSitesRoute: AppSitesRoute,
  AppStaffRoute: AppStaffRoute,
  AppWorkersRoute: AppWorkersRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkerRoute: WorkerRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
